### PR TITLE
feat: update footer and stats respo layout

### LINKED ISSUE #105: Update the footer
- Add `Stablecoin` (https://balanced.network/stablecoin/)
- Remove Revue and Telegram from the social links

Screen Shot 2022-04-06 at 9 40 34 AM

You can view this live on balanced.network.

### PR DESCRIPTION
**Pull request by hetfly**
close #105

### CODE REVIEW

**Comment by hetfly** [comment]
@parrot9design I also fixed the respo version of the footer and the main stat items on top and bottom of the page.
image
image

**Comment by hetfly** [comment]
removed

**Review by parrot9design — APPROVED** [review]

**Comment by lifeofkaizen** [comment]
@octocat512 this is good to merge

**Comment by parrot9design** [comment]
@octocat512 this is good to merge.

**Comment by parrot9design** [comment]
@octocat512 bumping this again. This PR is ready (overdue) to merge.

**Pull request merged**
