### PR TITLE
feat: show limits

### LINKED ISSUE #114: Stability Fund Stats: Add max cap per pool.
Personally, I want to know the max cap per pool.
image

### PR DESCRIPTION
**Pull request by hetfly**
close #114

### CODE REVIEW

**Comment by parrot9design** [comment]
Looks good! Just needs an adjustment for smaller screen sizes to keep the table headers in line with the content:
Screen Shot 2022-06-18 at 10 30 49 AM

**Comment by hetfly** [comment]
@parrot9design thanks, check it out now

**Review by parrot9design — APPROVED** [review]
This looks good to merge, thanks @hetfly!

**Comment by parrot9design** [comment]
One issue (which we can address separately) is that if you're looking at this on a mobile (or at least, on an iPhone), whenever you tap the date picker, it zooms in. Can we prevent it from doing that?

**Pull request merged**
