### PR TITLE
Migrate backend APIs

### LINKED ISSUE #146: Migrate to new backend API

### PR DESCRIPTION
**Pull request by hetfly**
close #146

### CODE REVIEW

**Comment by BennyOptions** [comment]
TVL takes a very long time to load - see video. General load times seem much slower than previously


https://user-images.githubusercontent.com/43685868/223542780-9f795b22-77b0-4233-af88-a38eb178f254.mov

**Comment by hetfly** [comment]
@BennyOptions weird, is your connection alright? Could you try again please? This is what I get 

https://user-images.githubusercontent.com/13098459/223546678-cbc774c0-d965-4ed3-81ae-0fafa83f9a37.mov

**Comment by parrot9design** [comment]
They're taking a while to load for me, as well:

https://user-images.githubusercontent.com/63842577/223553478-ce15aa8d-26d4-4542-898b-aec029c33dc3.mov

The TVL, exchange section, and earnings section on /performance-details seemed to be the worst.

**Comment by BennyOptions** [comment]
@hetfly interesting, fwiw I'm using google chrome, no VPN or anything. Maybe my computer is just slow haha, but seems to also happen to parrot9

**Review by parrot9design — APPROVED** [review]

**Pull request merged**
