### PR TITLE
Feat/add stability fund info

### LINKED ISSUE #109: Add a Stability Fund section to the Performance Details page
If [this 24-hour proposal](https://app.balanced.network/vote/proposal/45) is approved, we’ll need to add a `Stability fund` section to the Performance Details page ASAP to show the current balance of stablecoins.

Mockup is here: http://balanced-development.s3-website-us-east-1.amazonaws.com/stats-dev/financial-statements/

Should only display the balances of bnUSD, IUSDC, and USDS

Related: https://github.com/balancednetwork/balanced-java-contracts/pull/102

### PR DESCRIPTION
**Pull request by hetfly**
close #109

### CODE REVIEW

**Comment by octocat512** [comment]
@hetfly please reference this [PR](https://github.com/balancednetwork/balanced-network-info/pull/112).
FYI, we published @balancednetwork packages that were shared in the web app and the stats website. 
https://www.npmjs.com/org/balancednetwork

**Comment by octocat512** [comment]
Merge the [PR ](https://github.com/balancednetwork/balanced-network-info/pull/112)into this PR.

**Review by parrot9design — APPROVED** [review]
Great work, @hetfly! Haven't checked against the contracts to confirm the numbers, but from a UI perspective, this looks ready to merge.

**Comment by octocat512** [comment]
@hetfly please remove the types/balanced-sdk-core folder. Please check the PR again to eliminate the dead code.

**Pull request merged**
