### PR TITLE
fix: update texts, order tokens in TokenSection.tsx, add plural strin…

### PR DESCRIPTION
**Pull request by hetfly**
…g ending for tokens and dollars

### CODE REVIEW

**Comment by hetfly** [comment]
Regarding the change from Balance Token -> Balance Tokens and Balanced Dollar -> Balanced Dollars
Since the names are queried from geometry backend I hardcoded the "s" ending for names ending with token or dollar to avoid more complex solutions. 
I don't like this very much, but couldn't think of anything else.
Is it ok @hieunguyenebox ?

**Comment by WeiLi512** [comment]
@parrot9design I think the section is for the token name that is used on the smart contract side. Why we use plural nouns for the name of the token.

image

**Comment by parrot9design** [comment]
@WeiLi512 For the marketing site and docs, we always use the plural form as it sounds better. To be honest, it's not a huge deal either way, so if it does make the code ugly because you have to hardcode the `s` in, we can just leave it as is.

**Comment by WeiLi512** [comment]
@hetfly I think you can remove the hardcoded code. Please check the above comment.

**Comment by hetfly** [comment]
hardcoded 's' removed @WeiLi512

**Pull request merged**
