### PR TITLE
feat: init sorting

### LINKED ISSUE #92: Add the ability to sort the Tokens and Exchange sections by column header
You should be able to click any of the table headings to change how the data is sorted.

Screen Shot 2022-02-08 at 12 20 09 PM

Screen Shot 2022-02-08 at 12 20 19 PM

### PR DESCRIPTION
**Pull request by hetfly**
close #92

### CODE REVIEW

**Comment by parrot9design** [comment]
It looks like the token price is ordered by the 24 hour % change. Let's order it by $ value instead.
Screen Shot 2022-02-18 at 1 34 48 PM

Otherwise, this looks all good. The animation could start to feel a little too slow/over the top for people who are chronic re-sorters, but let's see how it goes. We can always cut it back if it starts to get annoying.

**Comment by parrot9design** [comment]
> @parrot9design Isn't it better to keep price sorting based on 24h change? Seems to me as relatively more important info to sort by. If you want to sort by token value, marketcap is better metric for that anyway.

I guess it depends. Sorting based on 24h change is good for spotting trends, but sorting by $ value makes it easier to compare prices, particularly of stablecoins. As for which is better...is there any way we could have the option to sort by both?

**Comment by hetfly** [comment]
> I guess it depends. Sorting based on 24h change is good for spotting trends, but sorting by $ value makes it easier to compare prices, particularly of stablecoins. As for which is better...is there any way we could have the option to sort by both?

I couldn't think of anything not too much invasive for the UI. 
Changed sorting based on price, we can revisit this later maybe with some feedback from the community

**Comment by parrot9design** [comment]
> > I guess it depends. Sorting based on 24h change is good for spotting trends, but sorting by $ value makes it easier to compare prices, particularly of stablecoins. As for which is better...is there any way we could have the option to sort by both?
> 
> I couldn't think of anything not too much invasive for the UI. Changed sorting based on price, we can revisit this later maybe with some feedback from the community

Sounds great, thanks @hetfly!

**Review by parrot9design — APPROVED** [review]

**Comment by lijac** [comment]
Looks absolutely stunning!

**Pull request merged**
